//
//  TaskEditorViewController.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorDisplayLogic: AnyObject {

}

final class TaskEditorViewController: UIViewController {
  private var interactor: TaskEditorBusinessLogic!
  var router: (TaskEditorRoutingLogic & TaskEditorDataPassing)!

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder) {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup() {
    let dataStore = TaskEditorDataStore()
    let worker = TaskEditorWorker()
    let presenter = TaskEditorPresenter(displayer: self)
    let interactor = TaskEditorInteractor(dataStore: dataStore, worker: worker, presenter: presenter)
    let router = TaskEditorRouter(dataStore: dataStore, viewController: self)

    self.interactor = interactor
    self.router = router
  }
}

extension TaskEditorViewController: TaskEditorDisplayLogic {
  
}
