//
//  TaskListPresenter.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskListPresentationLogic: AnyObject {

}

final class TaskListPresenter {
  private weak var displayer: TaskListDisplayLogic?
  
  init(displayer: TaskListDisplayLogic) {
    self.displayer = displayer
  }
}

extension TaskListPresenter: TaskListPresentationLogic {
  
}
