//
//  TaskListInteractor.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

protocol TaskListBusinessLogic: AnyObject {
  
}

final class TaskListInteractor {
  private let dataStore: TaskListDataStoreProtocol
  private let worker: TaskListWorkerProtocol
  private let presenter: TaskListPresentationLogic
  
  init(dataStore: TaskListDataStoreProtocol,
       worker: TaskListWorkerProtocol,
       presenter: TaskListPresentationLogic) {
    
    self.dataStore = dataStore
    self.worker = worker
    self.presenter = presenter
  }
}

extension TaskListInteractor: TaskListBusinessLogic {
  
}
