//
//  TaskEditorPresenter.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorPresentationLogic: AnyObject {

}

final class TaskEditorPresenter {
  private weak var displayer: TaskEditorDisplayLogic?
  
  init(displayer: TaskEditorDisplayLogic) {
    self.displayer = displayer
  }
}

extension TaskEditorPresenter: TaskEditorPresentationLogic {
  
}
