//
//  TaskEditorRouter.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol TaskEditorRoutingLogic: AnyObject {
  
}

protocol TaskEditorDataPassing: AnyObject {
  var dataStore: TaskEditorDataStoreProtocol { get }
}

final class TaskEditorRouter: TaskEditorDataPassing {
  var dataStore: TaskEditorDataStoreProtocol
  private weak var viewController: TaskEditorViewController?
  
  init(dataStore: TaskEditorDataStoreProtocol,
       viewController: TaskEditorViewController) {
    
    self.dataStore = dataStore
    self.viewController = viewController
  }
}

extension TaskEditorRouter: TaskEditorRoutingLogic {
  
}
