//
//  TaskEditorViewController.swift
//  todo
//
//  Created by Okhan Okbay on 7.11.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

final class TaskEditorViewController: UIViewController {
  @IBOutlet private weak var textView: UITextView!
  var taskEditorOperationEnded: TextHandler!
  var initialText: String?
  
  override func viewDidLoad() {
    super.viewDidLoad()

    configureNavigationItem()
    configureTextView()
  }
}

// MARK: TaskEditorViewController Scoped Methods

extension TaskEditorViewController {
  
  func configureNavigationItem() {
    navigationItem.rightBarButtonItem = .init(barButtonSystemItem: .done, target: self, action: #selector(didTapDoneButton))
  }
  
  func configureTextView() {
    if let initialText = initialText {
      textView.text = initialText
    }
    
    textView.becomeFirstResponder()
  }
  
  @objc func didTapDoneButton() {
    taskEditorOperationEnded(textView.text)
    navigationController?.popViewController(animated: true)
  }
}
